### ISSUE TITLE
SQL exception:  Grouping error

### ISSUE THREAD

**Issue by lordn-n** [lexik/LexikMonologBrowserBundle#6]
I'm getting this exception after a clean install of my Symfony2 project:

```
An exception occurred while executing 'SELECT l.level, l.level_name, COUNT(l.id) AS count FROM monolog_entries l GROUP BY l.level ORDER BY l.level DESC': SQLSTATE[42803]: Grouping error: 7 ERROR: column "l.level_name" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT l.level, l.level_name, COUNT(l.id) AS count FROM mono... ^
```

My configuration is the following:

```YAML
# app/config/parameters.yml
parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
   ...
```

```YAML
# app/config/config.yml
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging:   false
        profiling: false
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Lexik monolog browser
lexik_monolog_browser:
    doctrine:
        connection_name: default
        table_name: monolog_entries

monolog:
    handlers:
        main:
            type:         fingers_crossed # or buffer
            level:        error
            handler:      lexik_monolog_browser
        app:
            type:         buffer
            action_level: info
            channels:     app
            handler:      lexik_monolog_browser
        lexik_monolog_browser:
            type:         service
            id:           lexik_monolog_browser.handler.doctrine_dbal
```

What could it be?
